services:
  demo-java:
    image: ${IMAGE_URI}
    container_name: demo-java-app
    environment:
      SPRING_PROFILES_ACTIVE: mongo

      # REMOTO SOLO por URI (nada de DB_HOST=mongo)
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
    ports:
      - "${APP_PORT:-8081}:8081"
    networks: [demo-net]
    restart: unless-stopped

networks:
  demo-net:
    driver: bridge