services:
  mongo:
    image: mongo:8
    container_name: demojava-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-demo}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-demo}
      MONGO_INITDB_DATABASE: ${DB_NAME:-demo}
    networks:
      - demo-net
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  demo-java:
    image: ${IMAGE_URI:-demo-java-local}
    container_name: demo-java-app
    environment:
      SPRING_PROFILES_ACTIVE: mongo
      DB_ENGINE: mongo

      # Local o remoto (si pones DB_HOST apuntando a Atlas NO sirve,
      # Atlas debe ir por URI -> SPRING_DATA_MONGODB_URI)
      DB_HOST: ${DB_HOST:-mongo}
      DB_PORT: ${DB_PORT:-27017}

      DB_NAME: ${DB_NAME:-demo}
      DB_USER: ${DB_USER:-demo}
      DB_PASSWORD: ${DB_PASSWORD:-demo}

      # ✅ Atlas aquí (si existe, Spring usará esto)
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI:-}

    ports:
      - "${APP_PORT:-8081}:8081"
    depends_on:
      - mongo
    networks:
      - demo-net
    restart: unless-stopped

networks:
  demo-net:
    driver: bridge

volumes:
  mongo_data: