# Configuración generada por el Sistema de Gestión de Aplicaciones

app.nombre=prueba
app.descripcion=
app.lenguaje=JAVA
app.baseDatos.tipo=MYSQL
app.baseDatos.nombre=demo
app.baseDatos.usuario=demo
app.baseDatos.password=
app.cicd.proveedor=GITLAB
app.cicd.repoGit=https://gitlab.com/davidtome97/demojavamongo.git
app.cicd.sonarProjectKey=sonar-ddddd
app.despliegue.puertoInterno=
app.despliegue.nombreImagenEcr=demo2
