# ✅ Si hay URI (Atlas), úsala. Si está vacía, NO aplica.
spring.data.mongodb.uri=${MONGODB_URI:}

# ✅ Solo para LOCAL (cuando NO hay URI)
spring.data.mongodb.host=${DB_HOST:mongo}
spring.data.mongodb.port=${DB_PORT:27017}
spring.data.mongodb.database=${DB_NAME:demo}
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=${DB_USER:}
spring.data.mongodb.password=${DB_PASSWORD:}

# en mongo desactiva JPA/DataSource
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration